language: go

go:
- "1.14"

os:
- linux
- osx

script: go test -v ./... && go build -o prime-distribution-$TRAVIS_OS_NAME

deploy:
  provider: releases
  api_key:
    secure: maV+bAm+am7rIpmuSlzGvNRPZVDdMHoU3SrKLZBw4PsWYoKMhbK/AwVRybPFb2iruQUcEHD1l8bTY4yChfTJq2kEq72K9t84f8r2UOBUiLCVPZWDC/P02iptw59o0D9VH36+O/Wvt2UbaNLI8o0V7/2tMj2ddGvSbJFv0M0aNo5CdM6krw7EKO7zqz3ibpUq9g5GSiTnZ43moRcoZPCnEQNHnRlVmBbHEjweekxO3Vt7zoxBctipklZ8V40t1/m4XtamZf0J3zB54uw4ROn2/19mYCcwC5cyy974Ca318B+HdTZpEU1IuY0ArI9j1Udb6J/N6v49buNAl69C305foHe25sBhmq5+mELfKiRjCFEgivTPcthgevS7Ld0yNzG5Ie2jzlPLiwdbS9vhEBTuPkD6Fyx7GIPjHC1Bv/8h1cZavvWkxa/wh2hKxj5gYxkxzyYx8YiZh0RK8478OmzLt3d0Wmam9uAaqRlRrS2fSA5yW3BemxbBBm/y9myiHLuFkIdp7SDBQhwYgiB4O82v+mTOLGpT2QABMtuIDKNNxzioPmdhVUGfqu+M7y2sGp6OC0PI5ABLcplG6rtQEkd3Z6Mag3xHr9wsbAX/YlL+Vc9ak3X660v9aZCG65kaxNCNg9ir5Gshstpzl8PlrwNQhXH1WfKB2jOGHoucuSpW7Eo=
  file_glob: true
  file: prime-distribution-*
  skip_cleanup: true
  on:
    repo: olivierlemasle/prime-distribution
